base_url = "https://umukodes.netlify.app"
title = "Mukziez"
description = "Peer into Mukziez's thoughts"

compile_sass = true
generate_feed = true
minify_html = true
build_search_index = false
taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
# highlight_theme = "ayu-light"

[extra]
# author = "Godswill Umukoro"
# github = "https://github.com/godswillumukoro"
timeformat = "%B %e, %Y"                   # e.g. June 14, 2021

[[extra.menu]]
name = "Archive"
url = "/"

[[extra.menu]]
name = "Tags"
url = "tags"

[extra.footer]
info = 'Powered by <a href="https://www.getzola.org" target="_blank">Zola</a> and <a href="https://github.com/semanticdata/mabuya">Mabuya</a>.'
